Agostino - Correlatori con metodo di Dublino. Ora il codice include tutti i correlatori possibili. In QuenchedSpectrum/ ho inserito l'applicazione mk_dmesons che genera le configurazioni di gauge e misura i correlatori.
git-svn-id: file:///Users/pica/Downloads/GitClone/svnrep/suN/HiRep@46 37a69121-b030-0410-a54a-fdca83ffee47

diff --git a/QuenchedSpectrum/Makefile b/QuenchedSpectrum/Makefile
--- a/QuenchedSpectrum/Makefile
+++ b/QuenchedSpectrum/Makefile
@@ -24,7 +24,7 @@ MODS := amalloc field_alloc
 MOD_OBJS := $(MOD_OBJS) $(patsubst %, $(TOPDIR)/$(MODDIR)/%.o, $(MODS))
 
 MODDIR := Observables
-MODS := avr_plaquette quark_propagator mesons
+MODS := avr_plaquette quark_propagator mesons dublin_mesons
 MOD_OBJS := $(MOD_OBJS) $(patsubst %, $(TOPDIR)/$(MODDIR)/%.o, $(MODS))
 
 MODDIR := Random
@@ -32,7 +32,7 @@ MODS := gauss random_suNg ranlxs ranlxd random_fields
 MOD_OBJS := $(MOD_OBJS) $(patsubst %, $(TOPDIR)/$(MODDIR)/%.o, $(MODS))
 
 MODDIR := Update
-MODS := cabmar staples update_hb random_su2 Dphi representation random_momenta random_spinor_field
+MODS := cabmar staples update_hb random_su2 Dphi representation random_momenta random_spinor_field find_spec_limits
 MOD_OBJS := $(MOD_OBJS) $(patsubst %, $(TOPDIR)/$(MODDIR)/%.o, $(MODS))
 
 MODDIR := Error
@@ -44,7 +44,7 @@ MODS := base_stat jacknife
 MOD_OBJS := $(MOD_OBJS) $(patsubst %, $(TOPDIR)/$(MODDIR)/%.o, $(MODS))
 
 MODDIR := Inverters
-MODS := linear_algebra cg_mshift MINRES_mshift g5QMR_mshift MINRES
+MODS := linear_algebra cg_mshift MINRES_mshift g5QMR_mshift MINRES eva jacobi
 MOD_OBJS := $(MOD_OBJS) $(patsubst %, $(TOPDIR)/$(MODDIR)/%.o, $(MODS))
 
 qspectrum: $(OBJS) $(MOD_OBJS)
@@ -53,6 +53,11 @@ qspectrum: $(OBJS) $(MOD_OBJS)
 	echo " done." || echo " failed."
 
 mk_mesons: mk_mesons.o $(MOD_OBJS)
+	echo -n Linking [$@]... 
+	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ mk_mesons.o $(MOD_OBJS) &&\
+	echo " done." || echo " failed."
+
+mk_dmesons: mk_dmesons.o $(MOD_OBJS)
 	echo -n Linking [$@]... 
 	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ mk_mesons.o $(MOD_OBJS) &&\
 	echo " done." || echo " failed."
