Added mk_prop.c: takes a list of configurations and computes the propagator for them.
NB NB NB NB NB NB NB NB NB NB NB NB NB NB NB NB NB NB
The propagator computed in quark_propagator is now saved in double precision!!!!
NB NB NB NB NB NB NB NB NB NB NB NB NB NB NB NB NB NB



git-svn-id: file:///Users/pica/Downloads/GitClone/svnrep/suN/HiRep@74 37a69121-b030-0410-a54a-fdca83ffee47

diff --git a/QuenchedSpectrum/Makefile b/QuenchedSpectrum/Makefile
--- a/QuenchedSpectrum/Makefile
+++ b/QuenchedSpectrum/Makefile
@@ -2,7 +2,7 @@ TOPDIR = ..
 
 SRCS = qspectrum.c
 
-default: qspectrum mk_mesons
+default: qspectrum mk_mesons mk_prop
 
 MKDIR=$(TOPDIR)/Make
 include $(MKDIR)/MkRules
@@ -24,7 +24,7 @@ MODS := amalloc field_alloc spinor_field_alloc
 MOD_OBJS := $(MOD_OBJS) $(patsubst %, $(TOPDIR)/$(MODDIR)/%.o, $(MODS))
 
 MODDIR := Observables
-MODS := avr_plaquette quark_propagator mesons dublin_mesons
+MODS := avr_plaquette quark_propagator mesons 
 MOD_OBJS := $(MOD_OBJS) $(patsubst %, $(TOPDIR)/$(MODDIR)/%.o, $(MODS))
 
 MODDIR := Random
@@ -32,7 +32,7 @@ MODS := gauss random_suNg ranlxs ranlxd random_fields
 MOD_OBJS := $(MOD_OBJS) $(patsubst %, $(TOPDIR)/$(MODDIR)/%.o, $(MODS))
 
 MODDIR := Update
-MODS := cabmar staples update_hb random_su2 Dphi representation random_momenta random_spinor_field find_spec_limits
+MODS := cabmar staples update_hb random_su2 Dphi representation random_momenta random_spinor_field 
 MOD_OBJS := $(MOD_OBJS) $(patsubst %, $(TOPDIR)/$(MODDIR)/%.o, $(MODS))
 
 MODDIR := Error
@@ -44,8 +44,13 @@ MODS := base_stat jacknife
 MOD_OBJS := $(MOD_OBJS) $(patsubst %, $(TOPDIR)/$(MODDIR)/%.o, $(MODS))
 
 MODDIR := Inverters
-MODS := linear_algebra cg_mshift MINRES_mshift g5QMR_mshift MINRES eva jacobi dirac_eva
+MODS := linear_algebra cg_mshift MINRES_mshift g5QMR_mshift MINRES
 MOD_OBJS := $(MOD_OBJS) $(patsubst %, $(TOPDIR)/$(MODDIR)/%.o, $(MODS))
+
+mk_prop: mk_prop.o $(MOD_OBJS)
+	echo -n Linking [$@]... 
+	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ mk_prop.o $(MOD_OBJS) &&\
+	echo " done." || echo " failed."
 
 qspectrum: $(OBJS) $(MOD_OBJS)
 	echo -n Linking [$@]... 
