This should be a working status
A&A



git-svn-id: file:///Users/pica/Downloads/GitClone/svnrep/suN/HiRep@192 37a69121-b030-0410-a54a-fdca83ffee47

diff --git a/RHMC/Makefile b/RHMC/Makefile
--- a/RHMC/Makefile
+++ b/RHMC/Makefile
@@ -30,7 +30,7 @@ MODS := gauss random_suNg ranlxs ranlxd random_fields
 MOD_OBJS := $(MOD_OBJS) $(patsubst %, $(TOPDIR)/$(MODDIR)/%.o, $(MODS))
 
 MODDIR := Update
-MODS := Dphi staples update_hb random_su2 representation random_momenta random_spinor_field update_rhmc leapfrog local_action force0 copy_gfield find_spec_limits rational_functions force_rhmc O2MN_multistep cabmar
+MODS := Dphi staples update_hb random_su2 representation random_momenta random_spinor_field update_rhmc update_hmc leapfrog local_action force0 copy_gfield find_spec_limits rational_functions force_rhmc O2MN_multistep cabmar
 MOD_OBJS := $(MOD_OBJS) $(patsubst %, $(TOPDIR)/$(MODDIR)/%.o, $(MODS))
 
 MODDIR := Error
@@ -49,12 +49,12 @@ MODDIR := RHMC
 MODS := rhmc_utils
 MOD_OBJS := $(MOD_OBJS) $(patsubst %, $(TOPDIR)/$(MODDIR)/%.o, $(MODS))
 
-rhmc_OBJS = $(MOD_OBJS) 
+rhmc_OBJS = $(MOD_OBJS)
 
-rhmc: $(OBJS) $(MOD_OBJS)  rhmc.o
-	echo -n "Linking [$@]..." 
-	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(OBJS) $(MOD_OBJS) &&\
-	echo " done." || ( echo " failed." && false )
+#rhmc: $(OBJS) $(MOD_OBJS)
+#	echo -n "Linking [$@]..." 
+#	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(OBJS) $(MOD_OBJS) &&\
+#	echo " done." || ( echo " failed." && false )
 
 
 include $(MKDIR)/MkRules
