Static potential via Wilson loops.
Observables/wilsonloops.c : The function ara_temporalwilsonloops(...)
computes temporal wilson loops in the All-R-Approach, using the
Bresenham algorithm as in hep-lat/0005018.

Utils/HYP_smearing.c : Utilities for HYP smearing (hep-lat/0103029).

StaticPotential/mk_wilsonloops.c : The main application to compute
ARA wilson loops from saved configurations, and with HYP smearing.

StaticPotential/tune_HYP_smearing.c : The main application to find
the best weights for HYP smearing on a set of saved configurations.




git-svn-id: file:///Users/pica/Downloads/GitClone/svnrep/suN/HiRep@142 37a69121-b030-0410-a54a-fdca83ffee47

diff --git a/StaticPotential/Makefile b/StaticPotential/Makefile
--- a/StaticPotential/Makefile
+++ b/StaticPotential/Makefile
@@ -1,8 +1,8 @@
 TOPDIR = ..
 
-SRCS = mk_wilsonloops.c
+SRCS = mk_wilsonloops.c tune_HYP_smearing.c
 
-default: mk_wilsonloops
+default: mk_wilsonloops tune_HYP_smearing
 
 MKDIR=$(TOPDIR)/Make
 include $(MKDIR)/MkRules
@@ -16,7 +16,7 @@ MODS := archive logger read_input endian
 MOD_OBJS := $(MOD_OBJS) $(patsubst %, $(TOPDIR)/$(MODDIR)/%.o, $(MODS))
 
 MODDIR := Utils
-MODS := suN_utils time boundary_conditions
+MODS := suN_utils time boundary_conditions HYP_smearing
 MOD_OBJS := $(MOD_OBJS) $(patsubst %, $(TOPDIR)/$(MODDIR)/%.o, $(MODS))
 
 MODDIR := Memory
@@ -43,9 +43,15 @@ MODDIR := Statistics
 MODS := base_stat jacknife
 MOD_OBJS := $(MOD_OBJS) $(patsubst %, $(TOPDIR)/$(MODDIR)/%.o, $(MODS))
 
+
 mk_wilsonloops: cinfo.c $(OBJS) $(MOD_OBJS)
 	echo -n Linking [$@]... 
-	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(OBJS) $(MOD_OBJS) &&\
+	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ mk_wilsonloops.o $(MOD_OBJS) &&\
+	echo " done." || echo " failed."
+
+tune_HYP_smearing: cinfo.c $(OBJS) $(MOD_OBJS)
+	echo -n Linking [$@]... 
+	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ tune_HYP_smearing.o $(MOD_OBJS) &&\
 	echo " done." || echo " failed."
 
 
