Fixed some Makefiles.
git-svn-id: file:///Users/pica/Downloads/GitClone/svnrep/suN/HiRep@165 37a69121-b030-0410-a54a-fdca83ffee47

diff --git a/Make/MkRules b/Make/MkRules
--- a/Make/MkRules
+++ b/Make/MkRules
@@ -5,13 +5,15 @@
 
 include $(MKDIR)/MkFlags
 
+SHELL = /bin/bash
+
 .%.d: SRC=$(patsubst .%.d,%.c,$@)
 .%.d: %.c 
 	$(MAKE) -C $(INCDIR) all
-	echo "Generating dependences for [$(SRC)]...\c"
+	echo -n "Generating dependences for [$(SRC)]..."
 	$(GCC) -MM -MG -MT "$@ $(patsubst .%.d,%.o,$@)" $(CPPFLAGS) $(SRC) > $@ &&\
 		echo "RBLD = rebuild" >> $@ &&\
-	echo " done." || echo " failed."
+	echo " done." || ( echo " failed." && false )
 
 #if test "$(findstring .d,$(lastword $(MAKEFILE_LIST)))" = ""; then \
 
@@ -28,7 +30,7 @@ endif
 	  if test "$(findstring .d,$(MAKEFILES))" = ""; then \
 	    MAKEFILES="$(patsubst %.o,.%.d,$@)" $(MAKE) $@ ;\
 	  else \
-	    echo "Compiling [$(CURDIR)/$@]...\c" ;\
+	    echo -n "Compiling [$(CURDIR)/$@]..." ;\
 	    $(CC) -c $(CFLAGS) $(CPPFLAGS) $(SRC) &&\
 	    echo " done." || ( echo " failed." && false) ;\
 	  fi ;\
@@ -68,7 +70,7 @@ $(patsubst %,clean-%,$(SUBDIRS)):
 	$(MAKE) -C $(patsubst clean-%,%,$@) clean
 
 clean:: $(patsubst %,clean-%,$(SUBDIRS))
-	echo "Cleaning $(CURDIR)...\c"
+	echo -n "Cleaning $(CURDIR)..."
 	rm -f *.o *.rpo *~ *.il *.dyn *.ii *.s .*.d
 	echo " done."
 
diff --git a/TestProgram/PureGauge/Makefile b/TestProgram/PureGauge/Makefile
--- a/TestProgram/PureGauge/Makefile
+++ b/TestProgram/PureGauge/Makefile
@@ -44,7 +44,7 @@ MOD_OBJS := $(MOD_OBJS) $(patsubst %, $(TOPDIR)/$(MODDIR)/%.o, $(MODS))
 $(MAIN): %: %.o $(MOD_OBJS)
 	echo -n Linking [$@]... 
 	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $< $(MOD_OBJS) &&\
-	echo " done." || echo " failed."
+	echo " done." || ( echo " failed." && false )
 
 
 .PHONY: default
diff --git a/Update/Makefile b/Update/Makefile
--- a/Update/Makefile
+++ b/Update/Makefile
@@ -6,6 +6,6 @@ MKDIR = $(TOPDIR)/Make
 include $(MKDIR)/MkRules
 
 approx_data.db:
-	echo "Writing rational approximation database... \c"
+	echo -n "Writing rational approximation database..."
 	( cd remez && cat approx_* | ./mkappdata.pl >../$@ && cd .. \
-		&& echo "done." ) || ( echo "failed." && false )
+		&& echo " done." ) || ( echo " failed." && false )
diff --git a/Utils/Makefile b/Utils/Makefile
--- a/Utils/Makefile
+++ b/Utils/Makefile
@@ -9,9 +9,9 @@ MKDIR = $(TOPDIR)/Make
 include $(MKDIR)/MkRules
 
 suN_exp.c: $(MKDIR)/MkFlags $(WRREPR) TMPL/suN_exp.c.tmpl
-	echo "Writing representation code...\c"
+	echo -n "Writing representation code..."
 	$(WRREPR) $(NG) TMPL/suN_exp.c.tmpl > $@ &&\
-	  echo " done." || echo " failed."
+	  echo " done." || ( echo " failed." && false )
 
 clean::
 	rm -f suN_exp.c
