Cleaned files for Windows line-endings and trailing whitespaces

diff --git a/Make/MkRules b/Make/MkRules
--- a/Make/MkRules
+++ b/Make/MkRules
@@ -1,5 +1,5 @@
 ###############################################################################
-# Copyright (c) 2008,2014, Claudio Pica                                       #   
+# Copyright (c) 2008,2014, Claudio Pica                                       #
 # All rights reserved.                                                        #
 ###############################################################################
 
@@ -118,10 +118,10 @@ RBLD = $(if $(DFILES),,rebuild)
 	fi
 
 
-$(INCDIR)/.autoheaders.h: $(MKDIR)/MkFlags 
+$(INCDIR)/.autoheaders.h: $(MKDIR)/MkFlags
 	if  test "$(call _testdir, $@)" != ""; then \
 	  $(MAKE) -C $(dir $@) $(notdir $@) ;\
-	fi 
+	fi
 
 %.c:
 	if  test "$(call _testdir, $@)" != ""; then \
@@ -204,7 +204,7 @@ LDFLAGS += -lm
 
 define LINK_template
 $(1): $(1).o $$($(1)_OBJS) $$(COMMON_OBJS) $$(LIBS)
-	echo -n "$$(_col_link)Linking$$(_col_norm) $$(call _cfname,$$@)..." 
+	echo -n "$$(_col_link)Linking$$(_col_norm) $$(call _cfname,$$@)..."
 	$$(CC) -o $$@ $$< $$($(1)_OBJS) $$(COMMON_OBJS) $$(LDFLAGS) &&\
 	echo " $$(_cdone)" || ( echo " $$(_cfailed)" && false )
 endef
@@ -215,7 +215,7 @@ $(foreach prog,$(EXES),$(eval $(call LINK_template,$(prog))))
 define RUNTEST_template
 echo -n "$(_col_test)["$(1)"]$(_col_norm) ..." ; rm -f debug out_0 err_0 ; \
 export OMPI_MCA_btl_base_warn_component_unused=0 ;\
-$(RUNTEST) ./$(1) -i $(1).in >/dev/null && echo " $(_cpassed)" || ( echo " $(_cfailed)" && touch .test_failed && tail -n 80 out_0 ); 
+$(RUNTEST) ./$(1) -i $(1).in >/dev/null && echo " $(_cpassed)" || ( echo " $(_cfailed)" && touch .test_failed && tail -n 80 out_0 );
 endef
 
 runtests:
