Dphi.c          The function D_eopre which computes the even/odd                 preconditioned Dirac operator (without g5) is added.
archive.c       Functions to read/write pseudofermions are added.

archive_henty.c A function to read the gauge field from a text file
                according to the format used by David Henty is added.

Geometry        The even/odd sites are redefined in such a way that the
                point of global coordinates (0,0,0,0) is always odd.

pta_qprop.c     Error foxed: g5D_eopre replaced with D_eopre.

random_spinor.c Tool to generate and save a pseudofermion.

check_diracoperator_4.c Compute the gamma matices from the Dirac operator
                and verify the indipendence on the set of sources used
                to compute them.

avr_plaquette.c A function to compute the plaquette separately in each    
                direction is added.




git-svn-id: file:///Users/pica/Downloads/GitClone/svnrep/suN/HiRep@108 37a69121-b030-0410-a54a-fdca83ffee47

diff --git a/Spectrum/Makefile b/Spectrum/Makefile
--- a/Spectrum/Makefile
+++ b/Spectrum/Makefile
@@ -1,8 +1,8 @@
 TOPDIR = ..
 
-SRCS = mk_mesons.c random_cnfg.c
+SRCS = mk_mesons.c random_cnfg.c random_spinor.c
 
-default: mk_mesons random_cnfg
+default: mk_mesons random_cnfg random_spinor
 
 MKDIR=$(TOPDIR)/Make
 include $(MKDIR)/MkRules
@@ -12,7 +12,7 @@ MODS := geometry_init geometry_mpi_eo communications
 MOD_OBJS := $(MOD_OBJS) $(patsubst %, $(TOPDIR)/$(MODDIR)/%.o, $(MODS))
 
 MODDIR := IO
-MODS := archive logger read_input
+MODS := archive logger read_input archive_henty archive_old
 MOD_OBJS := $(MOD_OBJS) $(patsubst %, $(TOPDIR)/$(MODDIR)/%.o, $(MODS))
 
 MODDIR := Utils
@@ -56,6 +56,11 @@ mk_mesons: mk_mesons.o $(MOD_OBJS)
 random_cnfg: random_cnfg.o $(MOD_OBJS)
 	echo -n Linking [$@]... 
 	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ random_cnfg.o $(MOD_OBJS) &&\
+	echo " done." || echo " failed."
+
+random_spinor: random_spinor.o $(MOD_OBJS)
+	echo -n Linking [$@]... 
+	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ random_spinor.o $(MOD_OBJS) &&\
 	echo " done." || echo " failed."
 
 
