Change in Makefiles: echo -n --> echo "\c" for compatibility with sh shell. In IO/endian.c, changed BIG_ENDIAN --> _BIG_ENDIAN and similarly for LITTLE_ENDIAN, to fix bug in gnu libc.
git-svn-id: file:///Users/pica/Downloads/GitClone/svnrep/suN/HiRep@158 37a69121-b030-0410-a54a-fdca83ffee47

diff --git a/Include/Makefile b/Include/Makefile
--- a/Include/Makefile
+++ b/Include/Makefile
@@ -9,14 +9,14 @@ include $(MKDIR)/MkRules
 
 
 suN.h suN_types.h: $(MKDIR)/MkFlags $(WRHEAD)
-	echo -n "Writing suN headers..."
+	echo "Writing suN headers...\c"
 	$(WRHEAD) $(NG) $(REPR) &&\
 		echo " done." || echo " failed."
 
 suN_repr_func.h: $(MKDIR)/MkFlags $(WRREPR) TMPL/suN_repr_func.h.tmpl
-	echo -n "Writing representation header..."
+	echo "Writing representation header...\c"
 	$(WRREPR) $(NG) TMPL/suN_repr_func.h.tmpl > $@ &&\
-		echo " done." || echo " failed."
+		echo " done." || ( echo " failed." && false )
 
 
 clean::
diff --git a/Make/MkRules b/Make/MkRules
--- a/Make/MkRules
+++ b/Make/MkRules
@@ -8,7 +8,7 @@ include $(MKDIR)/MkFlags
 .%.d: SRC=$(patsubst .%.d,%.c,$@)
 .%.d: %.c 
 	$(MAKE) -C $(INCDIR) all
-	echo -n Generating dependences for [$(SRC)]...
+	echo "Generating dependences for [$(SRC)]...\c"
 	$(GCC) -MM -MG -MT "$@ $(patsubst .%.d,%.o,$@)" $(CPPFLAGS) $(SRC) > $@ &&\
 		echo "RBLD = rebuild" >> $@ &&\
 	echo " done." || echo " failed."
@@ -28,9 +28,9 @@ endif
 	  if test "$(findstring .d,$(MAKEFILES))" = ""; then \
 	    MAKEFILES="$(patsubst %.o,.%.d,$@)" $(MAKE) $@ ;\
 	  else \
-	    echo -n Compiling [$(CURDIR)/$@]... ;\
+	    echo "Compiling [$(CURDIR)/$@]...\c" ;\
 	    $(CC) -c $(CFLAGS) $(CPPFLAGS) $(SRC) &&\
-	    echo " done." || echo " failed.";\
+	    echo " done." || ( echo " failed." && false) ;\
 	  fi ;\
 	else \
 	  $(MAKE) -C $(dir $@) $(notdir $@) ;\
@@ -68,7 +68,7 @@ $(patsubst %,clean-%,$(SUBDIRS)):
 	$(MAKE) -C $(patsubst clean-%,%,$@) clean
 
 clean:: $(patsubst %,clean-%,$(SUBDIRS))
-	echo -n Cleaning $(CURDIR)...
+	echo "Cleaning $(CURDIR)...\c"
 	rm -f *.o *.rpo *~ *.il *.dyn *.ii *.s .*.d
 	echo " done."
 
diff --git a/RHMC/Makefile b/RHMC/Makefile
--- a/RHMC/Makefile
+++ b/RHMC/Makefile
@@ -52,9 +52,9 @@ MODS := rhmc_utils
 MOD_OBJS := $(MOD_OBJS) $(patsubst %, $(TOPDIR)/$(MODDIR)/%.o, $(MODS))
 
 rhmc: cinfo.c $(OBJS) $(MOD_OBJS)
-	echo -n Linking [$@]... 
+	echo "Linking [$@]...\c" 
 	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(OBJS) $(MOD_OBJS) &&\
-	echo " done." || echo " failed."
+	echo " done." || ( echo " failed." && false )
 
 
 .PHONY: default
