I rewrote the MkRules files and made changes to the other Makefiles as necessary. This substancially speed up compilation times.
git-svn-id: file:///Users/pica/Downloads/GitClone/svnrep/suN/HiRep@166 37a69121-b030-0410-a54a-fdca83ffee47

diff --git a/Include/Makefile b/Include/Makefile
--- a/Include/Makefile
+++ b/Include/Makefile
@@ -4,6 +4,9 @@ SRCS =
 
 all: suN.h suN_types.h suN_repr_func.h
 
+.autoheaders.h: all
+	echo done > $@
+
 MKDIR = $(TOPDIR)/Make
 include $(MKDIR)/MkRules
 
@@ -11,7 +14,7 @@ include $(MKDIR)/MkRules
 suN.h suN_types.h: $(MKDIR)/MkFlags $(WRHEAD)
 	echo -n "Writing suN headers..."
 	$(WRHEAD) $(NG) $(REPR) &&\
-		echo " done." || echo " failed."
+		echo " done." || ( echo " failed." && false )
 
 suN_repr_func.h: $(MKDIR)/MkFlags $(WRREPR) TMPL/suN_repr_func.h.tmpl
 	echo -n "Writing representation header..."
@@ -20,6 +23,6 @@ suN_repr_func.h: $(MKDIR)/MkFlags $(WRREPR) TMPL/suN_repr_func.h.tmpl
 
 
 clean::
-	rm -f *~ suN.h suN_types.h suN_repr_func.h HEADERS.DONE.h
+	rm -f *~ suN.h suN_types.h suN_repr_func.h .autoheaders.h
 
 .PHONY: all
diff --git a/Make/MkRules b/Make/MkRules
--- a/Make/MkRules
+++ b/Make/MkRules
@@ -8,27 +8,26 @@ include $(MKDIR)/MkFlags
 SHELL = /bin/bash
 
 .%.d: SRC=$(patsubst .%.d,%.c,$@)
-.%.d: %.c 
-	$(MAKE) -C $(INCDIR) all
-	echo -n "Generating dependences for [$(SRC)]..."
-	$(GCC) -MM -MG -MT "$@ $(patsubst .%.d,%.o,$@)" $(CPPFLAGS) $(SRC) > $@ &&\
-		echo "RBLD = rebuild" >> $@ &&\
-	echo " done." || ( echo " failed." && false )
+.%.d: %.c $(INCDIR)/.autoheaders.h
+	if test $(dir $@) = "./"; then \
+	  echo -n "Generating dependences for [$(SRC)]..." ;\
+	  $(GCC) -MM -MG -MT "$@ $(patsubst .%.d,%.o,$@)" $(CPPFLAGS) $(SRC) > $@ &&\
+	  echo " done." || ( echo " failed." && false ) ;\
+	  MAKEFILES="$@" $(MAKE) $@ ;\
+	else \
+	  $(MAKE) -C $(dir $@) $(notdir $@) ;\
+	fi
 
-#if test "$(findstring .d,$(lastword $(MAKEFILE_LIST)))" = ""; then \
+DFILES = $(findstring .d,$(MAKEFILES))
+RBLD = $(if $(DFILES),,rebuild)
 
-ifeq ($(RBLD),rebuild)
-  RBLD=
-else
-  RBLD=rebuild
-endif
 %.o: SRC=$(patsubst %.o,%.c,$@) 
 %.o: DEP=$(patsubst %.o,.%.d,$@)
-%.o: %.c $(RBLD)
+%.o: %.c $(MKDIR)/MkFlags $(RBLD)
 	if  test $(dir $@) = "./"; then \
-	  MAKEFILES="$(patsubst %.o,.%.d,$@)" $(MAKE) $(patsubst %.o,.%.d,$@) ;\
-	  if test "$(findstring .d,$(MAKEFILES))" = ""; then \
-	    MAKEFILES="$(patsubst %.o,.%.d,$@)" $(MAKE) $@ ;\
+	  if test "$(DFILES)" = ""; then \
+	    $(MAKE) $(DEP) ;\
+	    MAKEFILES="$(DEP)" $(MAKE) $@ ;\
 	  else \
 	    echo -n "Compiling [$(CURDIR)/$@]..." ;\
 	    $(CC) -c $(CFLAGS) $(CPPFLAGS) $(SRC) &&\
@@ -38,24 +37,19 @@ endif
 	  $(MAKE) -C $(dir $@) $(notdir $@) ;\
 	fi
 	
-%.h: $(MKDIR)/MkFlags rebuild
+$(INCDIR)/.autoheaders.h: $(MKDIR)/MkFlags  
 	if  test $(dir $@) != "./"; then \
 	  $(MAKE) -C $(dir $@) $(notdir $@) ;\
-	else \
-	  if test ! -f $@ ; then $(MAKE) -C $(INCDIR) $@ ; fi \
-	fi
+	fi 
 
 .DEFAULT:
 	if  test $(dir $@) != "./"; then \
 	  $(MAKE) -C $(dir $@) $(notdir $@) ;\
 	fi
 
+SRCS += $(patsubst %,%.c,$(EXES))
 OBJS = $(SRCS:.c=.o)
 _MkRules_default_target: $(OBJS)
-
-headers:
-	$(MAKE) -C $(INCDIR) all
-
 
 WRHEAD = $(MKDIR)/Utils/write_suN_headers.pl
 WRREPRDIR = $(MKDIR)/Utils/autosun
@@ -64,7 +58,7 @@ WRREPR = $(WRREPRDIR)/writeREPR
 $(WRREPR): $(MKDIR)/MkFlags
 	REPRESENTATION=$(REPR) make -C $(WRREPRDIR) $(notdir $@)
 
-.PHONY: rebuild clean $(patsubst %,clean-%,$(SUBDIRS)) _MkRules_default_target
+.PHONY: rebuild clean $(patsubst %,clean-%,$(SUBDIRS)) cleanall $(patsubst %,cleanall-%,$(SUBDIRS)) _MkRules_default_target
 
 $(patsubst %,clean-%,$(SUBDIRS)):
 	$(MAKE) -C $(patsubst clean-%,%,$@) clean
@@ -74,6 +68,26 @@ clean:: $(patsubst %,clean-%,$(SUBDIRS))
 	rm -f *.o *.rpo *~ *.il *.dyn *.ii *.s .*.d
 	echo " done."
 
+$(patsubst %,cleanall-%,$(SUBDIRS)):
+	$(MAKE) -C $(patsubst cleanall-%,%,$@) cleanall
+
+cleanall:: $(patsubst %,cleanall-%,$(SUBDIRS))
+	echo -n "Cleaning $(CURDIR)..."
+	rm -f *.o *.rpo *~ *.il *.dyn *.ii *.s .*.d
+	echo " done."
+	echo -n "Removing EXEs in $(CURDIR)..."
+	rm -f $(EXES)
+	echo " done."
+
 cinfo.c: $(MKDIR)/MkFlags $(MKDIR)/MkRules $(MKDIR)/Utils/cinfo.sh
 	$(MKDIR)/Utils/cinfo.sh $(MKDIR) $(TOPDIR) $(MACRO)
+
+define LINK_template
+$(1): $(1).o $$($(1)_OBJS) $$(COMMON_OBJS)
+	echo -n Linking [$$@]... 
+	$$(CC) $$(CFLAGS) $$(LDFLAGS) -o $$@ $$< $$($(1)_OBJS) $$(COMMON_OBJS) &&\
+	echo " done." || ( echo " failed." && false )
+endef
+
+$(foreach prog,$(EXES),$(eval $(call LINK_template,$(prog))))
 
diff --git a/RHMC/Makefile b/RHMC/Makefile
--- a/RHMC/Makefile
+++ b/RHMC/Makefile
@@ -1,11 +1,9 @@
 TOPDIR = ..
-
-SRCS = rhmc.c
-
-default: rhmc
-
 MKDIR=$(TOPDIR)/Make
-include $(MKDIR)/MkRules
+
+EXES = rhmc
+
+default: $(EXES)
 
 MODDIR := Geometry
 MODS := geometry_init geometry_mpi_eo test_geometry_mpi blocked eo_lexi lexi communications
@@ -51,11 +49,15 @@ MODDIR := RHMC
 MODS := rhmc_utils
 MOD_OBJS := $(MOD_OBJS) $(patsubst %, $(TOPDIR)/$(MODDIR)/%.o, $(MODS))
 
-rhmc: cinfo.c $(OBJS) $(MOD_OBJS)
-	echo -n "Linking [$@]..." 
-	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(OBJS) $(MOD_OBJS) &&\
-	echo " done." || ( echo " failed." && false )
+rhmc_OBJS = $(MOD_OBJS)
 
+#rhmc: $(OBJS) $(MOD_OBJS)
+#	echo -n "Linking [$@]..." 
+#	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(OBJS) $(MOD_OBJS) &&\
+#	echo " done." || ( echo " failed." && false )
+
+
+include $(MKDIR)/MkRules
 
 .PHONY: default
 
