Perl script generates fine but needs to be tested.

diff --git a/Include/Makefile b/Include/Makefile
--- a/Include/Makefile
+++ b/Include/Makefile
@@ -4,7 +4,7 @@ MKDIR = $(TOPDIR)/Make
 #the default target cannot start with .
 default: .autoheaders.h
  
-.autoheaders.h: suN.h suN_types.h suN_repr_func.h macro_opt.h
+.autoheaders.h: suN.h suN_types.h suN_repr_func.h macro_opt.h gpu_geometry.h
 	echo done > $@
 
 
@@ -19,9 +19,14 @@ suN_repr_func.h: $(MKDIR)/MkFlags TMPL/suN_repr_func.h.tmpl
 	$(WRREPR) $(NG) TMPL/suN_repr_func.h.tmpl > $@ &&\
 		echo " $(_cdone)" || ( echo " (_cfailed)" && false )
 
+gpu_geometry.h: $(MKDIR)/MkFlags $(MKDIR)/Utils/write_gpu_geometry.pl
+	echo -n "$(_col_write)Writing GPU geometry macros$(_col_norm)..."
+	$(MKDIR)/Utils/write_gpu_geometry.pl $(NG) $(REPR) $(WQUAT) $(GAUGE_GROUP) && \
+		echo " $(_cdone)" || ( echo " $(c_failed)" && false )
+
 
 clean::
-	rm -f *~ suN.h suN_types.h suN_repr_func.h macro_opt.h .autoheaders.h
+	rm -f *~ suN.h suN_types.h suN_repr_func.h macro_opt.h gpu_geometry.h .autoheaders.h
 
 include $(MKDIR)/MkRules
 
@@ -29,6 +34,8 @@ include $(MKDIR)/MkRules
 suN_repr_func.h: $(WRREPR)
 
 suN.h suN_types.h: $(WRHEAD)
+
+gpu_geometry.h: $(WRHEAD)
 
 macro_opt.h: $(MKDIR)/MkFlags
 	perl -e '$$_="$(CPPFLAGS)"."\n"; s/\s+/\n/g; s/-I\s*.*?\n//g; s/-D/#define /g; s/=/ /g; print; print "\n";' > $@
